service: refinery-pipeline

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 512
  environment:
    STAGE: ${self:provider.stage}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    API_TOKEN: ${env:API_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"

functions:
  processor:
    handler: dist/index.handler
    description: "Process scraped website content with AI enrichment"
    events:
      - httpApi:
          path: /process
          method: post
      - httpApi:
          path: /health
          method: get

package:
  individually: true
  patterns:
    - dist/index.js
    - "!node_modules/**"
    - "!src/**"
    - "!.git/**"
    - "!*.md"
